API_TOKEN = '###############################################'
SERVER_ID = '################'
CHANNEL_ID = '-##########################'
BOT_TOKEN = '#########################################'
TITLE = 'Network Traffic over the Last 1 Week'
CAPTION = 'Network Traffic over the Last 1 Week (SERVER-1)'
TIME = '10:00'